mongodb/mongo-tools

mongoimport/common_test.go, mongoimport/csv_test.go, mongorestore/filepath_test.go, mongorestore/mongorestore_test.go
Updates to fix broken tests after --verbosity=N changes
=> TOOLS-743 test updates

common/db/openssl/openssl.go
See https://jira.mongodb.org/browse/TOOLS-1633 for a discussion of the problem.
=> TOOLS-1633 Suppress dialError data race warnings.

mongoreplay/playbackfile.go, mongorestore/metadata.go, test/qa-tests/jstests/restore/ordered_partial_index.js, test/qa-tests/jstests/restore/testdata/dump_ordered_partial_index/test/foo.metadata.json
https://mongodbcr.appspot.com/169230001/
=> TOOLS-1507 preserve order in partialFilterExpressions

set_goenv.sh
[TOOLS-2211](https://jira.mongodb.com/browse/TOOLS-2211)
=> TOOLS-2211 Migrate from Evergreen v2 toolchain to v3 toolchain

mongodump/mongodump.go, mongodump/oplog_dump.go
Looking at the copyDocumentFilter and oplogDocumentFilter filters, the filters don't actually modify the input slice, so I changed documentFilter to only return an error. I also got rid of copyDocumentFilter because it would be a no-op after this change. IMO, the documentFilter type should be changed to something like documentValidator, but I'm OK leaving it as-is if others think the current name makes sense.
=> TOOLS-2256 Refactor document filtering in mongodump

common.yml, release/platform/platform.go, release/release.go
In the spirit of this morning's retro discussion, I tried to push as much of this as possible into go code instead of tacking more functionality onto the evergreen config or putting it into shell scripts.
=> TOOLS-2443: Create zip and tarball archives in dist task

vendor/github.com/mongodb/mongo-tools-common/password/pass_util.go
Reverts mongodb/mongo-tools#190
=> Revert "TOOLS-2462: Password prompt does not work on windows"

common.yml
There was some extra reformatting bundled in with #195 that is causing major rebase conflicts with in-progress work. Putting up a quick PR to revert the reformatting, since that will be significantly less effort than working through the rebase!
=> TOOLS-2275: Revert common.yml reformatting

README.md
Just updating the README URL for our new docs, with some nice to have stuff for older docs.
=> Updating URL for the new database tools website

common.yml, release/platform/platform.go
Added extra platform per request in https://docs.google.com/document/d/1_IsRBSCMNs45H80alkai2HvN3WVOg5JUywuEoJKTD1I/edit#heading=h.8709ewb0mee0
=> TOOLS-2464: Update platform support

installer/deb/control
Small fix to resolve a leftover packaging TODO.
@pmeredit Do you know if there is also a maintainer field for the RPMs? I couldn't find one.
=> TOOLS-2506: Update maintainer email for linux packages

Gopkg.lock, Gopkg.toml, mongorestore/metadata.go, mongorestore/mongorestore_test.go, mongorestore/restore.go, vendor/github.com/mongodb/mongo-tools-common/bsonutil/indexes.go
Also uses ignoreUnknownIndexOptions option in the createIndexes command for servers >4.1.9.
=> TOOLS-2538 TOOLS-2536 Move index conversion logic to mongo-tools-common

common.yml, etc/repo-config.yml, release/env/env.go, release/evergreen/evergreen.go, release/release.go
The evg patch for this PR won't actually do anything, since the release task doesn't release anything on patchbuilds, but it would be good to get some eyes on it anyways.
=> TOOLS-2472: Automate linux package publishing

common.yml, release/evergreen/evergreen.go, release/release.go
Here is the plumbing for the correct names. I'm not sure how to actually run the curator task to make sure that this is working (I might need to be a project admin?), but we can talk about it tomorrow.
=> TOOLS-2539: Use correct names for packages

release/release.go
=> TOOLS-2539: Update release-linux to retry failures

RELEASE.md
This PR adds a `RELEASE.md` describing the versioning policy and release process for the tools
=> TOOLS-2441: Update release process documentation

common.yml, mongorestore/mongorestore_test.go
Tim, already approved the previous PR, so just adding you @rychipman
=> TOOLS-2628: Add 3.4 server tests.

CHANGELOG.md, RELEASE.md
A proposal for a process for keeping a public changelog for releases, and announcing the releases on the community forums.
=> TOOLS-2650 Create changelog for tools releases

release/release.go
The `push` task isn't patchable right now, but the following is a log snippet from a local run of `go run release/release.go linux-release` that demonstrates the new log output:
```
getting artifacts for ubuntu1804
starting curator for ubuntu1804-org-development
[ubuntu1804-org-development] [curator] 2020/08/12 12:09:54 [p=info]: curator version: 3c7e5577072012c2c564ff5fc4efd58dae42c8b5
starting curator for ubuntu1804-enterprise-development
[ubuntu1804-enterprise-development] [curator] 2020/08/12 12:09:59 [p=info]: curator version: 3c7e5577072012c2c564ff5fc4efd58dae42c8b5
starting curator for ubuntu1804-org-testing
[ubuntu1804-org-testing] [curator] 2020/08/12 12:10:04 [p=info]: curator version: 3c7e5577072012c2c564ff5fc4efd58dae42c8b5
starting curator for ubuntu1804-enterprise-testing …
```
=> TOOLS-2701: Log target linux repo in push task

Gopkg.lock, Gopkg.toml, vendor/github.com/mongodb/mongo-tools-common/bsonutil/indexes.go, vendor/github.com/mongodb/mongo-tools-common/password/pass_util.go, vendor/github.com/mongodb/mongo-tools-common/password/password.go
Dep ensure'd changes to MTC. The changes to `db.go` and `options.go` are from [TOOLS-2587](https://jira.mongodb.org/browse/TOOLS-2587).
=> TOOLS-2688: mongodump requires EOF when passing in the password as STDIN

common.yml
See: https://evergreen.mongodb.com/version/5f60bdb80305b97db9bd261c
=> TOOLS-2737 Add TLS options to Mac and Windows buildvariants

mongorestore/restore.go
Closes TOOLS-1856
( replaces https://github.com/mongodb/mongo-tools/pull/106 )
Not sure that it's still worth it though. Did some benchmarking with the following code: 
```
func BenchmarkRestore(b *testing.B) {
opts, err := mongorestore.ParseOptions([]string{"/home/feliixx/dump/dump"}, "", "")
restore, err := mongorestore.New(opts)
if err != nil {
b.Error(err)
}
b.StartTimer()
for i := 0; i < b.N; i++ {
b.StopTimer()
restore.SessionProvider.DB("test").Drop(nil)
b.StartTimer()
restore.Restore()
}
}
```
New code is a little bit faster, but most of the allocation ( > 90%) comes from this [line](https://github.com/mongodb/mongo-tools/blob/master/mongorestore/restore.go#L408) : 
`result.combineWith(NewResultFromBulkResult(bulk.InsertRaw(rawDoc)))`
so it doesn't make a huge difference for …
=> TOOLS-1856 Use a memory pool in mongorestore

mongorestore/restore.go
=> Fix for TOOLS-2744

CHANGELOG.md, RELEASE.md
I additionally made some changes to `RELEASE.md` since there were some steps that didn't quite make sense while I was doing the release.
=> TOOLS-2741: Release Database Tools 100.2.1

mongorestore/restore.go
This reverts commit 83e6dd5115e82ed8bb51428a0d78b12b5b66dac0.
It appears that the memory pool has cause signifcantly increased memory usage for a number of users.
I'm proposing that we revert it ASAP, and then re-open TOOLS-1856 with a note that we will need a solution for the memory usage issue if we want to add the memory pool back in.
=> TOOLS-2783: Revert "TOOLS-1856: Add a memory pool in mongorestore"

CHANGELOG.md, RELEASE.md
This patch includes the 100.3.1 changelog, plus a few updates to the release process checklist
=> TOOLS-2791: Update changelog for version 100.3.1

common.yml, release/platform/platform.go
I also renamed the race detector variant so it no longer looks like a zSeries task.
=> TOOLS-2927 Clean up the platforms list inside platform.go

CHANGELOG.md
I'm waiting for tests to finish on the waterfall before cutting the release, but I thought I'd get the changelog into review now.
=> TOOLS-2929 Add changelog for 100.4.1

etc/repo-config.yml
The edition should be `enterprise`, not `org`.
=> TOOLS-3155 Fix repo config for RHEL 8.3

CONTRIBUTING.md, README.md, common/db/optime.go, common/idx/index_catalog.go, mongofiles/mongofiles.go, mongoimport/mongoimport.go, mongoimport/typed_fields.go, mongoimport/typed_fields_test.go
- Update selective build command in README and various spelling fixes
- Add example to CONTRIBUTING page
- Remove golint warnings
=> Update README and various errata

CHANGELOG.md, RELEASE.md
Also updates the release process with clarifications.
=> Update changelog for 100.8.0

RELEASE.md, ticket-security-level.md
This PR documents a guideline for setting the Security Level of tools tickets.
=> TOOLS-3642 Document Security Level of TOOLS tickets

.github/CODEOWNERS, buildscript/sa.go, etc/github-codeowners-wrapper.sh, package-lock.json, package.json, precious.toml
There's also linting to make sure that we never add files without an owner. But right now all files are owned by the @mongodb/tar-osap  team.
=> TOOLS-3911 Add a CODEOWNERS file

RELEASE.md, SARIF.json, common.yml, installer/msi/LicensingFragment.wxs, installer/rpm/mongodb-database-tools.spec, release/release.go, scripts/regenerate-and-diff-sarif-report.sh, ssdlc/100.12.2.sarif.json, test/shell_common/libs/load_libs-8.2.js
This is very similar to what we do with the augmented SBOM.
=> TOOLS-3933 Add the SARIF report file to the repo and include it in release tarballs, etc.
