mongodb/mongo-tools

build.bat, set_gopath.bat, set_gopath.ps1, vendor.bat
Fixed set_gopath.bat to use symlinks just like set_gopath.sh does. This enables developers to run set_gopath.bat and not have to copy files before building. I've also included a set_gopath.ps1 for devs using a powershell prompt.  Finally, I've implemented vendor.sh and built.sh as batch files.
With these changes, I can clone the repo, run vendor.bat, run set_gopath.bat (or .ps1), run build.bat and get working versions of all the tools. In addition, when changing into each tools directory, I can run "go test" successfully.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/mongo-tools/46)
=> Enable Windows Developers

mongostat/stat_types.go
The json formatter doesn't display these fields when the engine is WiredTiger:
* flushes
* ar|aw
* qr|qw
But these fields are present in grid formatter and [documentation](https://docs.mongodb.org/manual/reference/program/mongostat/) doesn't mention that these fields are mmapv1 specific.
This patch fixes that.
=> TOOLS-1028 mongostat json has wrong mmapv1-specific fields

mongoexport/main/mongoexport.go, mongofiles/main/mongofiles.go, mongoimport/main/mongoimport.go, mongooplog/main/mongooplog.go, mongoreplay/execute.go, mongorestore/main/mongorestore.go
Arguments to defer are evaluated eagerly, hence should occur after any
error response is checked.
Fixes https://jira.mongodb.org/browse/TOOLS-1576
=> [TOOLS-1576] Move defer statements to after err checks.

common/db/connector.go, common/db/openssl/openssl.go, common/options/options.go, common/util/net.go
Jira: https://jira.mongodb.org/browse/TOOLS-1665
This change adds a hidden `--TCPKeepAliveSeconds` parameter that controls the period between TCP keepalives. A value of 0 means do not enable TCP keepalive. The default is 30-seconds.
A 30-second keepalive period means different things depending on the platform but it roughly corresponds to 5 minutes of inactivity. Check out how the [`setKeepAlivePeriod`](https://golang.org/search?q=setKeepAlivePeriod) function is defined on various platforms:
- On Windows, after 30-seconds 10 keep-alive probes will be sent every 30 seconds. This results in 5.5 minutes of keep-alive time. See https://golang.org/src/net/tcpsockopt_windows.go?h=setKeepAlivePeriod#L14 and https://msdn.microsoft.com/en-us/library/windows/desktop/dd877220(v=vs.85).aspx.
- On …
=> TOOLS-1665 Set TCP keepalive.

mongorestore/oplog.go
To test this I think we can copy `testdata/oplogdump` and corrupt one of the documents in oplog.bson. Then the `DecodedBSONSource` would error when decoding the corrupt document.
=> TOOLS-2102 Check for errors reading oplog file

bsondump/bsondump_test.go, build.sh, set_goenv.sh
[TOOLS-2179](https://jira.mongodb.com/browse/TOOLS-2179)
This PR allows the testBsondump to run on windows. The problem was that the binaries were being output without a Windows executable file extension, so they could never be run from a command-line like environment. The changes here ensure build.sh outputs the binaries with a .exe file extension if it detects it's being run in a Cygwin environment.
[evergreen patch](https://evergreen.mongodb.com/version/5c6c74557742ae4f5bebfd79)
=> TOOLS-2179 Fix testBsondump not running on Windows

mongodump/prepare.go
[TOOLS-2222](https://jira.mongodb.com/browse/TOOLS-2222)
=> TOOLS-2222 Mongodump should ignore config.transactions and config.transaction_coordinators

mongofiles/mongofiles.go, test/qa-tests/jstests/files/mongofiles_put.js
[TOOLS-2229](https://jira.mongodb.org/browse/TOOLS-2229)
The bug here is likely within mgo itself attempting to clean up orphan chunks when something goes wrong inserting into GridFS, but changing that behavior may break all other kinds of things within mgo and projects that depend on it. It's much easier just to perform a query here in mongofiles instead, which is what I've done.
[evg patch](https://evergreen.mongodb.com/version/5c786bb4850e614e333352bd)
=> TOOLS-2229 Fix mongofiles deletes chunks of existing file when failing to put_id with existing _id

mongoimport/common.go, mongoimport/common_test.go, mongoimport/csv_test.go, mongoimport/json.go, mongoimport/json_test.go, mongoimport/main/mongoimport.go, mongoimport/mongoimport.go, mongoimport/mongoimport_test.go, mongoimport/options.go, mongoimport/options_test.go, mongoimport/tsv_test.go, mongoimport/typed_fields_test.go
Some sort of change is necessary in mongo-tools-common/db/db.go to recognize "not master" errors from the server correctly due to a difference in how mgo and the new driver print command errors before this patch passes on Evergreen.
For the time being, I left in the dependency on bsonutil and the mgo BSON lib. Removing those can be done at a later time if needed.
=> TOOLS-1835 Port mongoimport to the new driver

mongodump/mongodump.go
Verified that this does not send an aggregate command to count the documents in the oplog by enabling command monitoring in the driver.
=> TOOLS-2068 Skip calling Count() on the oplog in mongodump

Gopkg.lock, Gopkg.toml, bsondump/main/bsondump.go, mongodump/main/mongodump.go, mongoexport/main/mongoexport.go, mongoexport/mongoexport.go, mongofiles/main/mongofiles.go, mongofiles/mongofiles.go, mongofiles/options.go, mongoimport/main/mongoimport.go, mongorestore/main/mongorestore.go, mongorestore/mongorestore.go, mongostat/main/mongostat.go, mongostat/stat_consumer/stat_consumer.go, mongotop/main/mongotop.go, test/qa-tests/jstests/export/type_case.js, test/qa-tests/jstests/libs/output.js, test/qa-tests/jstests/stat/stat_auth.js, test/qa-tests/jstests/stat/stat_custom_headers.js, test/qa-tests/jstests/stat/stat_discover_shard.js, test/qa-tests/jstests/stat/stat_rowcount.js, vendor/github.com/mongodb/mongo-tools-common/signals/signals.go, vendor/github.com/mongodb/mongo-tools-common/util/exit_code.go
[TOOLS-2253](https://jira.mongodb.org/TOOLS-2253)
The new exit codes are `util.ExitFailure` (1) and `util.ExitSuccess` (0)
=> TOOLS-2253 Eliminate distinct exit codes

Gopkg.lock, Gopkg.toml, mongodump/options.go, mongoexport/options.go, mongofiles/options.go, test/qa-tests/jstests/dump/read_preference_and_tags.js, vendor/github.com/mongodb/mongo-tools-common/db/read_preferences.go
This PR does the following:
- fixes the bug where a "primary" mode read preference could not be set
- fixes the bug where mongodump could not specify a read preference both in the uri and via --readPreference
- allows maxStalenessSeconds to be set via --readPreference
- allows multiple tag sets to be set via --readPreference
- updates the help output to describe how one should pass things in via --readPreference
The new help output is the following:
`      --readPreference=<string>|<json>            specify either a preference mode (e.g. 'nearest') or a preference json object (e.g. '{mode: "nearest", tagSets: [{a: "b"}], maxStalenessSeconds: 123}')`
Check the vendor files for the parsing changes. I have some unit tests written not present in this PR that will be go into mongo-tools-common …
=> TOOLS-2285 / TOOLS-2132 Read preference parsing improvements

Gopkg.lock, mongoimport/common.go, mongoimport/common_test.go, mongoimport/main/mongoimport.go, mongoimport/mongoimport.go, mongoimport/mongoimport_test.go, mongoimport/options.go, mongorestore/main/mongorestore.go, mongorestore/metadata.go, mongorestore/mongorestore.go, mongorestore/mongorestore_archive_test.go, mongorestore/mongorestore_test.go, mongorestore/oplog.go, mongorestore/oplog_test.go, mongorestore/options.go, mongorestore/restore.go, test/qa-tests/jstests/import/import_document_validation.js, test/qa-tests/jstests/restore/restore_document_validation.js, vendor/github.com/mongodb/mongo-tools-common/db/buffered_bulk.go, vendor/github.com/mongodb/mongo-tools-common/db/db.go
Based on this [design](https://docs.google.com/document/d/1U-ifRuBKV3QGTJsWVDRt4tJTdQ891jD1RJnjePifHuw/edit#).
Deviations from the design:
- input parsing errors, even for TSV and CSV, are considered failing errors. They are already implemented this way and it would entail more work to change them to be skippable errors than I imagined. If users request the feature it can be added in the future.
- Document validation errors were added to the list of skippable errors
- numDecodingWorkers does not need to be set to 1 in import, since there is already logic for ensuring multiple decoding workers maintain the order
As part of these changes, I also updated the logging to more accurately reflect the number of documents inserted and the number that failed. A "failure" means failed to write to …
=> TOOLS-2246 Rework maintainInsertionOrder and stopOnError

Gopkg.lock, test/qa-tests/jstests/restore/archive_stdout.js, vendor/github.com/mongodb/mongo-tools-common/archive/prelude.go
[TOOLS-2290](https://jira.mongodb.org/browse/TOOLS-2290)
This PR fixes a bug where collections that had '%' in their names could not be restored using `--archive`. 
The bug was caused by an extraneous unescape attempt when reading the archive prelude. When dealing with archives, escaping and unescaping of collection names should only be performed in the filesystem abstraction layer `PreludeExplorer`, but I had included one below that in the actual prelude parser.
=> TOOLS-2290 Fix mongorestore unable to restore collections with percents in names from archive

mongodump/prepare.go
I am sure that the exact number of records in the progress bar is not important enough to read the collection twice.
=> Use `EstimatedDocumentCount` instead `CountDocuments` for progress bar render

mongodump/mongodump.go, mongodump/prepare.go
Sets `intent.Location` in the default case when `--archive` isn't set. Also moves setting the `intent.Location` to `MongoDump.NewIntentFromOptions()` since it feels like it makes more sense for this to be done at initialization.
=> TOOLS-2350 Print the correct output location

mongoimport/mongoimport_test.go, mongoimport/tsv.go
Also stops passing a sessionProvider by value in checkOnlyHasDocuments().
EVG: https://evergreen.mongodb.com/version/5dd3d8462fbabe0ba7537376
=> Fix import tests for TSVs and on Windows 

common.yml
This PR creates the sign task, though it doesn't yet do any signing (since the artifacts we will sign, MSIs and linux packages, have not been created yet).
=> TOOLS-2449: Create sign task

mongorestore/mongorestore.go
Before, doing `cat ~/empty.bson | mongorestore --db test --collection cafes -` unnecessarily printed the following deprecation message on the first line:
```
2020-01-30T14:26:46.894-0500	the --db and --collection args should only be used when restoring from a BSON file. Other uses are deprecated and will not exist in the future; use --nsInclude instead
2020-01-30T14:26:46.895-0500	setting up a collection to be read from standard input
2020-01-30T14:26:46.895-0500	restoring to existing collection test.cafes without dropping
2020-01-30T14:26:46.895-0500	restoring test.cafes from -
2020-01-30T14:26:46.962-0500	no indexes to restore
2020-01-30T14:26:46.962-0500	finished restoring test.cafes (0 documents, 0 failures)
2020-01-30T14:26:46.962-0500	0 document(s) restored successfully. 0 …
```
=> TOOLS-2336: Fix deprecation message for --nsInclude when restoring from stdin

common.yml
There will be a single release of the tools for each platform we support (not separate enterprise and community releases, as there were when we released with the server). As such, we no longer need separate enterprise and community buildvariants for each supported platform.
Additionally, with the removal of mongoreplay from the tools, we do not need separate variants testing with and without SSL.
=> TOOLS-2473: Consolidate community, enterprise, and ssl buildvariants

common.yml, mongodump/metadata_dump.go, mongodump/mongodump_test.go, mongorestore/mongorestore.go
this PR fixes a failing format-go task and moves format-go, lint-go, vet, and lint-js into their own buildvariant for easier viewing from the github PR patchbuild widget
=> TOOLS-2489: Fix and separate static analysis tasks 

common.yml, release/env/env.go, release/platform/platform.go, release/release.go, set_goenv.sh
This PR contains some platform renaming that is better to do in a separate PR from the rest of 2442 for ease of testing. Also wrapped in some refactors/rationalizations of the helper functions and types we're using in the release/ dir.
Only requiring @pmeredit from the get-go, since it's mostly just internal refactors of code he and I have added in the release/ dir.
=> TOOLS-2442: Naming conventions and refactors

common.yml
Some facts about the build failure fixed here:
- The task failures appear to be the OOM killer killing mongorestore when it hits 3.1G or so of memory.
- When this task passes, peak memory usage does not look substantially lower (perhaps 2.9G instead of 3.1)
- The [first commit that failed](https://evergreen.mongodb.com/task/mongo_tools_rhel62_qa_dump_restore_with_gzip_current_0660bca4bee742d34d34c8cdbf91f4bb6ee552ba_19_10_25_19_20_11) doesn't _appear_ to contain anything that would cause memory usage to spike
- Logs for passing tests are deleted more aggressively, so I can't actually compare memory usage after the first failure to memory usage prior to that commit
For a "fix", I've modified this particular task to run on a bigger rhel62/ubuntu1604 box. It's not guaranteed to make the …
=> TOOLS-2490: Run memory-hungry task on larger linux boxes

common.yml
Jira: https://jira.mongodb.org/browse/TOOLS-2440
I copied over the [sqlproxy `"sign msi installer"` function](https://github.com/10gen/sqlproxy/blob/1add0bfe7e43375274a936ac427f3ffb3d083d14/.evg.yml#L411-L430) and just changed the working dir, key name and auth token. There might be something else, but I believe this was it.
=> TOOLS-2440: Sign MSI installer

release/release.go, release/version/version.go
There was one place where I needed to switch "cli" to "database". Wrapped in a couple other refactors.
=> TOOLS-2488: Update package naming and versioning

common.yml, release/platform/platform.go
Right now, our release task cannot run, because it requires the "sign" tasks from all distros to have run. The "sign" tasks are not running on all distros, because some distros are not yet available in evergreen.
This patch contains two commits. The first changes two distros to match seemingly equivalent distros that _do_ exist in evergreen. The second temporarily removes some distros that are not yet supported in evergreen. This second commit should be reverted in TOOLS-2505 once all the distros in question are available.
=> TOOLS-2464: Fix missing evergreen distros

common.yml, release/download/download.go, release/release.go
Jira: https://jira.mongodb.org/browse/TOOLS-2471
This PR adds JSON feed generation to our `release.go` file for the download center. It's modeled after the [server JSON here](http://downloads.mongodb.org.s3.amazonaws.com/full.json) (~14 MBs of text as a fair warning).
The first commit is a preliminary idea to make sure we're okay with the JSON format. Since we have no sign tasks for testing, I had to mess around with the boolean conditions, comment out AWS uploads, etc. to download the artifacts for a random commit hash. I'm not including those changes here though.
Here's a sample output of what the JSON looks like for the first 5 sign tasks of some commit:
```
$ go run release/release.go upload-release 9ebaaf60989732c5f869f5f5592aa34d3e351688
{
"Versions": [
{
"Version": "4.3.2", …
```
=> TOOLS-2471: Automate JSON download feed generation

common.yml, release/platform/platform.go
debian71 and ubuntu1204 have been disabled in evergreen, and are slated for complete removal. We need to remove them so that release automation work can proceed.
=> TOOLS-2523: Remove debian71 and ubuntu1204 platforms

common.yml, release/release.go
ex: https://evergreen.mongodb.com/version/5e974e85c9ec4478197fb998
=> TOOLS-2539: Use latest instead of githash

Gopkg.lock, Gopkg.toml, mongodump/metadata_dump.go, mongodump/mongodump_test.go, mongodump/prepare.go, vendor/github.com/mongodb/mongo-tools-common/util/file.go
Jira: https://jira.mongodb.org/browse/TOOLS-2529
Design Doc: [https://docs.google.com/document/d/...](https://docs.google.com/document/d/1LCsXHqjQrRWDzD1Of_pNX41pyQZqd231ni9uF9_noY8/edit#heading=h.qk6j6d5j4oc5)
Related PR: https://github.com/mongodb/mongo-tools/pull/233
This PR allows us to output a new filename format for collections whose names would result in filenames >255 characters long.
The functional change is in `prepare.go`, with a new unit test for `outputPath()`. There's also a tiny change in `mongo-tools-common` that I'll do separately after this PR gets approved.
=> TOOLS-2529: Output new filename format for long collection names

installer/rpm/mongodb-database-tools.spec
The deps listed in the RPM packages were making the database-tools package uninstallable on RHEL, SUSE, etc. While the deb packages don't seem to have any installation issues right now, the versions declared as dependencies seem likely to cause similar issues on debian and ubuntu in the future.
I went back to the server repo from before the tools were removed, and copied how they declared dependencies. Once the patch runs, I will manually verify that the rpms install successfully and report back here
=> TOOLS-2548: Declare linux deps as the server did

installer/rpm/mongodb-database-tools.spec
Jira: https://jira.mongodb.org/browse/TOOLS-2559
This fixes the `rm` error message in the rpm installer.
It seems tough to test this through `yum erase` or something like that, so I just tested it independently on a CentOS 8 VM since it's simple:
```
[vagrant@localhost ~]$ sudo yum install mongodb-org
...
[vagrant@localhost ~]$ rm /usr/doc/mongodb-database-tools
rm: cannot remove '/usr/doc/mongodb-database-tools': No such file or directory
[vagrant@localhost ~]$ rm -f /usr/doc/mongodb-database-tools
[vagrant@localhost ~]$
```
=> TOOLS-2559: Fix rm message when uninstalling tools rpm package

mongorestore/filepath.go
Jira: https://jira.mongodb.org/browse/TOOLS-2593
This just adds a clarifying comment for the change [here in this commit](https://github.com/mongodb/mongo-tools/commit/60114507c1f63057163eb415e87fd7f91a12bf6f#diff-c00634e277d3e3e4a379a8318bcd17d1R248). Lmk if you think something should be rephrased!
=> TOOLS-2593: Clarify where $admin dbs are skipped

release/release.go
Jira: https://jira.mongodb.org/browse/TOOLS-2609
We weren't correctly ignoring .sig files, since `path.Ext()` returns the extension with the dot included (this is done right for `upload-release` though).
I tested the change on the 100.0.2 release and entries with URLs ending in .sig got correctly replaced with ones ending in .rpm / .deb, e.g. :
```
"package": {
"url": "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-amazon-x86_64-4.3.2-106-ge09bae2c.sig",
"md5": "041f4dfbb7d3ef50e0bb921a17a9e511",
"sha1": "871b2f681166f7eff4557c307c6c9f09c03a16d1",
"sha256": "83d337f06b49a5db1f81676de06821bba466bef736ee8a4796c8eb3843930487"
}
```
became
```
"package": {
"url": "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-amazon-x86_64-4.3.2-106-ge09bae2c.rpm",
"md5": …
```
=> TOOLS-2609: Remove broken .sig file links from release json feed

common.yml, release/release.go
JIRA: https://jira.mongodb.org/browse/TOOLS-2644
This change just uses the barque service user's API key instead of LDAP username/password to auth because the LDAP server is not supported anymore.
=> TOOLS-2644: authenticate to barque using API key

Gopkg.lock, Gopkg.toml
TOOLS-2287 should have done this, but only revendors by patch, i.e. v.3.0.13. Instead, it should have bumped the major version, since it involved a breaking change.
The proper MTC version has now been created - this PR is to revendor on the Tools' side.
=> Revendor Tools to use v4.0.0 of MTC

common.yml
Tools analog to https://github.com/10gen/sqlproxy/pull/297
=> TOOLS-2669: Preserve structure of macos zip archives when notarizing

installer/deb/control
I have filed a tracking ticket to monitor new releases of Ubuntu and Debian or EOL Ubuntu 16.04 and Debian 8.1, whichever comes first:
https://jira.mongodb.org/browse/TOOLS-2684
=> TOOLS-2283: use libcomerr2 as long as we support Ubuntu 16.04 and Debian 8.1

CHANGELOG.md
@andf-mongodb found a bug in our linux packaging that was breaking the 4.4 linux repos, so we had to get a fix out ASAP, despite the fact that this is a very small release!
=> TOOLS-2685: Update CHANGELOG.md for 100.1.1

mongofiles/mongofiles.go, mongofiles/mongofiles_test.go, mongofiles/options.go, mongofiles/options_test.go
This PR should enable the user to query GridFS by regex, i.e. PCRE, over filenames. The command should be as follows:
`mongofiles ... get_regex "<regex>" --regexOptions "<options>"`
`<options>` are optional additional arguments to the underlying _$regex_ query -- the possible options are [enumerated in the reference manual](https://docs.mongodb.com/manual/reference/operator/query/regex/#op._S_options).
**Test Plan**: Include two integration tests to check the `get_regex` command -- one without any options specified, and the other with the option for case-insensitivity.
Additionally, include two unittests to similarly check for cases of user input including and not including server options.
=> TOOLS-2668: Create regex interface for getting files from remote FS in mongofiles

common.yml
There were two distinct problems causing build failures in the race-detector variant.
One was that some of our automation code tries to determine the platform from the build variant name. Since "ubuntu-race" is not itself a platform, I had to add a way to override the variant name.
The other was that a number of our integration tests have expansions that cause them to _always_ run with TLS on, while the race detector buildvariant was configured not to use SSL. The easy fix here was to change the race detector variant to use SSL, though I also filed https://jira.mongodb.org/browse/TOOLS-2694 to address the underlying configuration inconsistency
=> TOOLS-2693: Fix race detector build failures

installer/deb/control, installer/rpm/mongodb-database-tools.spec
Upgrades from MongoDB v4.2 to v4.4 were somewhat problematic due to
incorrect dependency resolution resulting in both the older
mongodb-*-tools package and this package being installed at the same
time, causing file conflicts. The dependency resolution is improved so
that the package manager has an easier time doing an automated upgrade.
=> TOOLS-2716 Improve package dependency resolution with older versions

RELEASE.md, common.yml
This PR updates the release process in RELEASE.md to use evergreen's tag-triggered versions for releases. `common.yml` has been updated with tags for the tasks that should run on tag-triggered versions.
=> TOOLS-2700: Use tag-triggered versions for releasing

release/release.go
Jira: https://jira.mongodb.org/browse/TOOLS-2706
We were getting the Unix epoch time because we weren't specifying a `ModTime` in the tar header, though the [Go documentation makes that kind of unclear](https://github.com/golang/go/blob/d7ab277eed4d2e5ede4f3361adf42d4ad76ced8f/src/archive/tar/common.go#L156) in my opinion. Then [this line in the header code](https://github.com/golang/go/blob/d7ab277eed4d2e5ede4f3361adf42d4ad76ced8f/src/archive/tar/writer.go#L89) ended up rounding an empty `time.Time{}` which just left it at the Unix epoch.
Either way, specifying `ModTime: time.Now()` seems to fix it:
```
// Before ----------------------------------------------------------------------------------------------
$ tar xf ./old-release.tgz
tar: …
```
=> TOOLS-2706: Fix implausibly old time stamps in tarballs

Gopkg.lock, Gopkg.toml, README.md, set_goenv.sh, vendor/github.com/mongodb/mongo-tools-common/json/scanner.go, vendor/github.com/mongodb/mongo-tools-common/set_goenv.sh
Reverts mongodb/mongo-tools#303
SUSE and ZAP build variants don't have go 1.15 installed, which is causing failures.
Sorry @varsha804, I have to revert this to do the 100.2.0 release. We can merge it again once the release is cut. Are there BUILD tickets to fix the missing go binaries on SUSE and ZAP?
=> Revert "TOOLS-2707: Build mongo-tools with go 1.15"

Gopkg.lock, Gopkg.toml, mongostat/mongostat.go, vendor/github.com/mongodb/mongo-tools-common/options/options.go
The connection string failure seems to be a result of [this](https://github.com/mongodb/mongo-tools/commit/2aa1d7079b20817d17649ff7b43b2d79b69f1c8e) code change. Since `opts.Port` and `opts.Host` are not set when a user only uses `--uri`, `fullhost` gets set to `localhost:27017`, thereby incorrectly rewriting the hostname to `localhost`.
Manual testing:
1. Atlas cluster
2. mlaunch cluster
3. `--discover` without a connection string
4. Connection string as a positional argument without `--uri`
=> TOOLS-2708: Atlas recommended connection string for mongostat doesn't work

common.yml, release/env/env.go, release/evergreen/evergreen.go, release/release.go
We needed to retrieve a single sign or dist task to push the releases. But GetTasksForRevision would get the tasks for both the commit and the git tag. This will PR ensure that we only get the tasks for the git tag.
=> TOOLS-2747 Get task lists from current build/version only

common.yml, release/aws/aws.go, release/download/download.go, release/evergreen/evergreen.go, release/release.go
In order to create a download page for all historical releases of the tools, we need a JSON feed that contains information on all release artifacts. The current `release.json` only contains the latest release.
This PR adds logic for generating a release feed that contains all releases. The feed is uploaded it to the S3 bucket as `full.json`. Generating the feed from scratch will download each artifact and calculate the required hashes. New releases will update the `full.json` without having to calculate the hashes for previous versions.
See the generated `full.json` here: https://fastdl.mongodb.org/tools/db/full.json
=> TOOLS-2687 Support a release feed with all historical releases

release/release.go
The macos 10.14 sign task is currently failing because Patrick changed his Apple password and forgot to change the corresponding evergreen variable -- should be fixed soon!
=> TOOLS-2767: Windows 64 dist task fails

mongofiles/mongofiles.go
Jira: https://jira.mongodb.org/browse/TOOLS-2775
With two sample files in GridFS:
```
$ mongofiles --db testDB list
2021-01-07T14:38:21.865-0500	connected to: mongodb://localhost/
sample-file-1.txt	0
sample-file-2.txt	0
```
Before change:
```
$ mongofiles --db testDB get_regex "sample*" --local sample-file.txt
2021-01-07T14:47:57.620-0500	connected to: mongodb://localhost/
2021-01-07T14:47:57.625-0500	finished writing to sample-file.txt
2021-01-07T14:47:57.625-0500	finished writing to sample-file.txt
```
^ `sample-file.txt` gets written twice
After change:
```
$ mongofiles --db testDB get_regex "sample*" --local sample-file.txt
2021-01-07T14:55:56.891-0500	connected to: mongodb://localhost/
2021-01-07T14:55:56.891-0500	Failed: cannot get multiple files with --local specified
```
I don't …
=> TOOLS-2775: Disallow multi-file get with --local

set_goenv.sh
Jira: https://jira.mongodb.org/browse/TOOLS-2795
Looks like all the variants are green, with a couple still scheduled: https://evergreen.mongodb.com/version/601307420305b9243b77846f
There's a system failure on Amazon Linux 64, though it's an unrelated permissions issue so that may be transient.
=> TOOLS-2795: Use system gcc instead of mongodbtoolchain gcc

release/release.go
Jira: https://jira.mongodb.org/browse/TOOLS-2800
Evergreen with variants that build rpm's: https://evergreen.mongodb.com/version/6019d3fc3627e0294b148ea6
This fixes the failing dist task on `amazon1-2018-test` albeit in a kind of ad hoc way. I spent some time looking into what was going on by comparing it with `amazon2-test` which works okay. I found some weird behavior, so I think this is the best we can do for the moment.
On the surface, the dist task was failing because `rpmbuild` was trying to create `/usr/src/rpm` which you'd need root permissions for. It got this directory from the `%{_topdir}` macro (I verified this with `rpm --eval "%{_topdir}"` and saw that it's `/usr/src/rpm`). That was strange given that every online doc says `%{_topdir}` should default to …
=> TOOLS-2800: Fix rpmbuild failing on amazon linux 1

mongodump/mongodump.go, mongodump/prepare.go
All of the tests passed after removing `system.indexes` dumping.
=> TOOLS-704: Remove system.indexes collection dumping from mongodump

build.go, buildscript/build.go, buildscript/sa.go, common.yml
Jira: https://jira.mongodb.org/browse/TOOLS-2805
This adds mongohouse's `go mod tidy` check to the tools. Building should now look like:
```
$ ./make build
START  | sa:modtidy
| exec: '/usr/local/bin/go mod tidy'
FINISH | sa:modtidy in 123.32094ms
START  | build
| rm: bin/bsondump
| exec: '/usr/local/bin/go run release/release.go get-version'
| exec: '/usr/bin/git rev-parse HEAD'
...
```
=> TOOLS-2805: Add mod tidy static analysis check for Go modules

test/qa-tests/jstests/top/mongotop_sharded.js
It looks like the test was checking that only the error message was printed. When we added some warning messages, they got printed too and the test started failing. The test now doesn't care if anything else is printed.
=> TOOLS-2796 Fix mongotop_sharded.js test

RELEASE.md
This ticket updates `RELEASE.md` in advance of the next release to account for a couple things:
- We should use the docs changes needed field on the ticket instead of manually filing downstream docsp tix
- Downstream CLOUDP ticket creation will have been automated (see PROG-4705).
=> TOOLS-2791: Update release process

mongorestore/filepath.go, mongorestore/filepath_test.go, mongorestore/metadata.go, mongorestore/metadata_test.go, mongorestore/mongorestore.go, mongorestore/mongorestore_test.go, mongorestore/options.go, mongorestore/options_test.go
I changed all usages of `NSOptions.{DB, Collection}` to `ToolOptions.Namespace.{DB, Collection}`, and added a test to `mongorestore/options_test.go`
=> TOOLS-2584: Restoring single BSON file should use db set in URI

build.go, buildscript/build.go, common.yml
Jira: https://jira.mongodb.org/browse/TOOLS-2807
This enables integration tests for `common`, including one options test with test type `SRVConnectionStringTestType`.
I think there's already sufficient platform coverage in mongo-tools for integration tests and that we don't need to sift through mtc's setup, but I can take a closer look if you think otherwise.
=> TOOLS-2807: Add common integration and srv tests

build.go, buildscript/sa.go, common.yml
Jira: https://jira.mongodb.org/browse/TOOLS-2824
Evergreen patch with task: https://evergreen.mongodb.com/version/606f6d6cd6d80a5fbdd77f56
This adds a task for `evergreen validate` in the buildscript and updates our Static Analysis buildvariant with it. Also adding some sample output of different scenarios below.
Everything succeeds:
```
$ go run build.go -v sa:evgvalidate
START  | sa:evgvalidate
| exec: '.../bin/evergreen validate --file common.yml'
FINISH | sa:evgvalidate in 971.621181ms
---------------
Completed in 971.889045ms
```
Breaking the syntax:
```
$ go run build.go -v sa:evgvalidate
START  | sa:evgvalidate
| exec: '.../bin/evergreen validate --file common.yml'
FAIL   | sa:evgvalidate in 807.488006ms
| error from `evergreen validate`: ERROR: load project error(s): error …
```
=> TOOLS-2824: Add static analysis task that runs `evergreen validate`

mongodump/mongodump_test.go
The resharding tests were failing on standalones because they require a replica set to test the oplog. These tests now skip standalones.
The test was also flaking on replica sets due to the timing between creating and dropping the collections in the test. I have modified the timing and it looks like it no longer flakes.
Evergreen patch: https://spruce.mongodb.com/version/60e4d55fe3c3312642105c74/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> TOOLS-2849 fix resharding tests

test/legacy42/jstests/tool/command_line_quotes.js
It looks like the mongo shell removed `MongoRunner.runMongoTool` function since 4.4. Besides, many failures in js-4.2 4.4 tests are because dataPath is defaulting to '/data/db/' which is read-only on many distros.
=> TOOLS-2893: fix legacy-js-tests 4.4 and 5.0

mongorestore/mongorestore_test.go
Thanks to the way timeseries collections are supported in TOOLS-2859, all that needs to be done for this ticket is adding tests for renaming timeseries collections.
=> TOOLS-2860 add timeseries rename tests

release/release.go
I'm a bit confused about when we should be pushing to the testing repos. The comment seems to imply that we should only be publishing rc versions... but we aren't doing any filtering of versions. Does barque filter out requests based on version strings?
=> TOOLS-2926 remove dev/test repos from stable releases

common.yml, release/platform/platform.go
Jira: https://jira.mongodb.org/browse/TOOLS-2938
Evergreen patch for added platform: https://spruce.mongodb.com/version/610955d70305b90f583aee5e/tasks
Only thing is that the `integration-4.0-mmapv1` task is failing [here](https://evergreen.mongodb.com/task_log_raw/mongo_tools_ubuntu1604_ppc64le_integration_4.0_mmapv1_patch_d727fdbbdda025b60ceac191df3219cbea96ffe7_610955d70305b90f583aee5e_21_08_03_14_42_49/0?type=T#L213) with the error:
```
Cannot start server with an unknown storage engine: mmapv1, terminating
```
I noticed the same issue on the RHEL 7.1 PPC64LE platform [here](https://evergreen.mongodb.com/task_log_raw/mongo_tools_rhel71_ppc64le_integration_4.0_mmapv1_d727fdbbdda025b60ceac191df3219cbea96ffe7_21_07_30_13_33_44/0?type=T#L202), but not on a non-PPC platforms like SUSE 12 …
=> TOOLS-2938: Re-add Ubuntu 16.04 PowerPC platform

common/db/db.go, common/options/options.go, common/options/options_test.go
When `loadBalanced` is set, we need to make sure we don't set `direct` or `replicaSet`. We were doing that by default in some situations.
We also now error if a user sets `loadBalanced` with `direct` or `replicaSet` in the URI.
I tested this manually on serverless and it looks good!
=> TOOLS-2937 Set loadbalanced option in db.configureClient()

common/failpoint/failpoint.go, common/failpoint/failpoint_disabled.go, common/failpoint/failpoint_test.go, common/options/options.go, common/options/options_fp.go, common/options/options_fp_disabled.go, common/options/options_test.go, common/password/pass_util.go, common/progress/progress_bar_test.go, linter.go, mongostat/stat_consumer/interactive_line_formatter.go
Currently we have a bug in the verbose flag parsing. The `SetVerbosity` function adds up the verbosity level every time when it's called. The reason for such logic is we wanna support command line flag such as 
`-v -v -v`(verbose level =3) or `-v --verbose=3`(verbose level =4)
However, this imposes a bug when `parseArgs`get called multiple times, we will multiple the verbose levels in the case. Currently `parseArgs` is get called both in `func (opts *ToolOptions) ParseArgs` and `ParseConfigFile`. 
There is no perfect solution for this bug right now because we cannot differentiate when `SetVerbosity` was called by a single `parseArgs` for a second time or by different `parseArgs` callers. So I made a little hacky fix.
I created a function `CallArgParser` to wrap `parseArgs` around. This …
=> MGOMIRROR-469: Fix verbosity bug when calling ParseArgs multiple times

common/options/options.go
I tried to change the order of the parameters to have the error messages more meaningful.
=> TOOLS-2983 - Swap arguments for error messages

common/db/buffered_bulk.go, common/db/buffered_bulk_test.go
Add the batch byte limit back. The byte limit does not take selectors into account so it won't be perfect for delete, update, and replace. But it should be good enough to keep memory usage in check in most cases.
=> TOOLS-2875 Add batch byte limit to BufferedBulkInserter

common.yml
This fixes the build issues with Go 1.17 on RHEL 6.2 by putting a much newer gcc toolchain (7) in the path.
=> TOOLS-3119 Enable devtoolset-7 on RHEL 6.2

common/bsonutil/bsonutil.go, common/bsonutil/bsonutil_test.go, common/idx/index_catalog.go, common/idx/index_catalog_test.go
Previously it always returned true because of a bug that had it always compare the left value to itself instead of the right.
I also added tests for this function and converted the existing tests in bsonutil_test.go to testify.
This also adds some additional protection in `IndexCatalog.DeleteIndexes` to prevent dropping more than 1 index.
=> Fix bsonutil.IsEqual

common/db/db.go, common/options/options.go
Previously, we didn't prompt for a password until we attempted to establish a
database connection. But before we did that we would call
`connstring.ConnString.Validate`, which would return an error if the user for
the connection was set but no password was provided.
This commit moves the prompt for the password to just before the call to
`Validate`, so we should never end up complaining about a missing password
before having a chance to prompt the user.
I tested this by hand with a few different patterns:
$> go run ./mongotop/main/ -u user --authenticationMechanism 'PLAIN'
$> go run ./mongotop/main/ -u user --password="" --authenticationMechanism 'PLAIN'
$> go run ./mongotop/main/ -u user --password=""
I tried this with a few different tools, including mongodump, mongorestore,
and …
=> TOOLS-2963 Move prompting for password to earlier in options processing

bsondump/bsondump_test.go, release/platform/platform.go
Not closing these caused the Windows issue where the tempdir couldn't be deleted.
=> TOOLS-3127 Fix Windows issues in CI

buildscript/build.go, go.mod, release/platform/platform.go, release/platform/platform_test.go, vendor/modules.txt
This also adds a test to check that our list of release platforms is in sync with what's in CI.
=> Remove Ubuntu 14.04 from the list of release platforms

common.yml, etc/repo-config.yml, release/platform/platform.go
This PR adds Ubuntu 22.04 x86 _and_ ARM to tools. I combined TOOLS-3058 and 3060 into one PR since they are similar. I followed [these instructions](https://github.com/mongodb/mongo-tools/blob/master/PLATFORMSUPPORT.md) (and the examples of existing ubuntu platforms) to add these two.
=> TOOLS-3058 + TOOLS-3060: Add Ubuntu 22.04 x86 and ARM to Tools

common.yml, release/release.go
~WIP~
~This PR adds 6.0 to the list of linux repos we release to. The only remaining step is adding the new variable to the mongo-tools evergreen project. I will update this PR with reviewers and relevant evergreen tasks when that is completed.~
This PR adds 6.0 to the list of linux repos we release to.
=> TOOLS-3130: Add 6.0 to list of linux repos we release to

common.yml, etc/repo-config.yml, release/platform/platform.go
This PR adds RHEL 9.0 x86 ~_and_ ARM~ to tools. ~Similar to the ubuntu 22.04 support I did earlier, I combined TOOLS-3054 and 3056 into one PR since they are similar.~
Update: the evergreen RHEL9 ARM distro does not have Go installed, so that ticket (3054) is blocked. I am keeping this PR open since it can still cover the work for 3056.
=> TOOLS-3056: Add RHEL9 x86 to Tools

common/db/db.go, common/options/options.go, common/options/options_test.go, common/password/password.go, mongostat/main/mongostat.go
I tested this by hand by running the following command:
go run ./mongodump/main/ --ssl --sslPEMKeyFile=./common/db/testdata/test-client-pkcs8-encrypted.pem
This prompted me for the password.
=> TOOLS-2913 Prompt for SSL key password when key is encrypted

etc/repo-config.yml
This commit fixes a typo in the RHEL 83 enterprise repo configuration to point to the enterprise address at repo.mongodb.com instead of the community address, repo.mongodb.org.
=> TOOLS-3179: update enterprise repo config

.gitignore, CONTRIBUTING.md, common.yml, common/testtype/types.go, mongorestore/mongorestore_txn_test.go, mongorestore/testdata/transactions-6.1.json, scripts/download_mongod_and_shell.py, scripts/download_mongod_and_shell.sh
The old hard-coded data no longer worked with Server 6.1 as the format for
updates has changed.
This PR adds a new file with the new format to be used with Server 6.1+.
In the future, we might want to instead generate this data in the test. That
was the first approach I tried, but it's not possible to generate many
transaction scenarios with the Server API as it stands. Specifically,
generating a set of partial transactions or `abortTransaction` and
`commmitTransaction` ops isn't possible, as these are only created based on
Server internals.
=> TOOLS-3185 Fix `TestMongorestoreTxns` failure with Server 6.1+

common/db/command.go, mongodump/mongodump_test.go
For some reason, on replica sets the error message is: "MongoServerError: no such command: 'atlasVersion'" and on sharded clusters the error message is: "MongoServerError: no such cmd: atlasVersion". 
This should account for both scenarios.
It turns out that a careful examination of the tests could have uncovered this: https://evergreen.mongodb.com/lobster/evergreen/complete-test/mongo_tools_rhel80_qa_tests_6.0_5d5402b0da91ca3a99a3d19f0265d98cae16a7f6_23_01_26_16_28_49/0#bookmarks=0%2C201199%2C460654&f~=000~sharded_fullrestore&f~=000~CommandNotFound&l=1&shareLine=201199 but it was quite hard to find after the fact (unless I know the exact failure mode).
=> BF-27644 Fix atlas proxy detection for sharded clusters

mongodump/mongodump.go, mongodump/mongodump_test.go
In the last 3 sub-tests of TestFailDuringResharding, it expects to fail when trying to dump the oplog, but it fails earlier, when it tries to create the intents for a database. This is a flaky test, most of the time it seems that it doesn't error early, but it is possible. We can skip creating the intents for the database if we specify a database, but it should still try to dump the oplog since its specified. This will ensure that it doesn't error on the earlier case and fail on that string comparison.
An example error is here: https://evergreen.mongodb.com/lobster/evergreen/test/mongo_tools_rhel83_s390x_integration_5.0_cluster_patch_5d5402b0da91ca3a99a3d19f0265d98cae16a7f6_63dbec3ed1fe074e9be5a1da_23_02_02_17_00_47/0/mongodump/#bookmarks=0%2C212&l=1&shareLine=131
=> TOOLS-3241 Fix TestFailDuringResharding so it doesn't sometimes error with a different message

common.yml
This is removed to prepare for upgrading Go to 1.19.
=> TOOLS-3249: Remove mongo-tools support for server version 3.4 on MacOS

common.yml, scripts/download_mongod_and_shell.py, scripts/download_mongod_and_shell.sh
- Changed edition name "community" to "targeted".
- Fixed a bug in `is_correct_download` method.
- Added arguments to specify `enterprise` edition for `aws-auth` tasks.
- [Tests](https://evergreen.mongodb.com/version/63ee78e82fbabe2cd3d7ba69)
=> TOOLS-3250: Fix aws-auth task failures

mongorestore/mongorestore_test.go
In older server versions, running `mongorestore` with `--noIndexRestore` creates a time series collection with no index. In the current `TestRestoreTimeseriesCollections` test, we check this by listing the indexes from the collection and expect no index to be created.
After [SERVER-66689](https://jira.mongodb.org/browse/SERVER-66689), the server automatically creates a default index on timestamp, metadata fields in time series collections upon creation. This causes `TestRestoreTimeseriesCollections` to [fail](https://parsley.mongodb.com/test/mongo_tools_amazon2_integration_latest_252cab37f1c57910db9eef2950a47ef83a5c4c50_23_02_16_17_12_14/0/mongorestore?bookmarks=0,854&shareLine=549). We should modify the test to check the server version and expect 1 index for server versions 6.3+.
=> TOOLS-3248: Change the expected behavior of --noIndexRestore in TestRestoreTimeseriesCollections for server 6.3+

common/db/command.go
This PR fixes test failures on server 3.4. This fix should make `IsAtlasProxy` method in `SessionProvider` backward compatible with server 3.4.
=> TOOLS-3255: Fix qa-tests-3.4

mongodump/mongodump_test.go, mongorestore/mongorestore_test.go
This PR adds new integration tests for Columnstore Indexes in `mongodump` and `mongorestore`. 
In `mongodump`:
- Create collections with a Columnstore Index created with `columnstoreProjection` key.
- Dump the collections.
- Check the dumped meta files for the correct number of Columnstore Indexes, Columnstore Index name, and `columnstoreProjection` key.
In `mongorestore`:
- Create a collection with a Columnstore Index created with `columnstoreProjection` key.
- Dump the collection and restore it. 
- Check the restored collection for the correct number of Columnstore Indexes, Columnstore Index name, and `columnstoreProjection` key.
=> TOOLS-3252: Test support for Columnstore Indexes

common.yml, test/legacy42/jstests/tool/restorewithauth.js, test/legacy42/lib/run_mongod.js
This PR creates a workaround to make the deprecated mongo shell compatible with new MongoDB server versions by overriding JS functions used by mongo shell. It is a temporary fix to re-enable `legacy-jstests` in mongo-tools failed due to deprecated mongo shell commands.
[evergreen](https://evergreen.mongodb.com/version/63f68ffc61837d43cb6cb4e9?redirect_spruce_users=true)
=> TOOLS-3202: Fix legacy-jstests failure with latest Server 

common.yml
Adds `integration`, `legacy-js-tests`, `aws-auth`, and `qa-tests` for server 6.3 in evergreen. 6.3 tests are added to the following buildvariants:
- Amazon Linux 64 v2
- Debian 10
- Debian 11
- MacOS 10.14
- RHEL 7.0
- RHEL 8.0
- SUSE 12
- SUSE 15
- Ubuntu 18.04
- Ubuntu 20.04
- Windows 64-bit
- ZAP ARM64 Ubuntu 18.04
- ZAP ARM64 Ubuntu 20.04
- Amazon Linux ARM v2
- RHEL 8.2 ARM
- ZAP PPC64LE RHEL 8.1
- ZAP s390x RHEL 7.2
=>  TOOLS-3251: Update common.yml to run tests with 6.3 

common.yml
There is no url to download server 6.3 from ZAP s390x RHEL 7.2 and ZAP PPC64LE RHEL 8.1. The 6.3 tests on these two systems should be removed.
=> TOOLS-3259: Remove 6.3 tests on `ZAP s390x RHEL 7.2` and `ZAP PPC64LE RHEL 8.1`

test/qa-tests/buildscripts/resmokeconfig/suites/core_tls.yml, test/qa-tests/jstests/libs/run_mongod.js
This PR fixes the qa-tests-latest by overriding `MongoRunner.runMongod` using `eval_prepend` shell option in the resmoke config file.
=> TOOLS-3257: Override deprecated mongo shell functions to fix qa-tests-latest

mongodump/mongodump_test.go, mongorestore/mongorestore_test.go
This PR checks `NotImplemented` error message when testing with columnstore indexes and skip those tests if error is `NotImplemented`.
=> TOOLS-3276: Skip columnstore indexes tests in mongodump and mongorestore if error is NotImplemented

common/options/options_test.go, mongodump/mongodump_test.go, mongorestore/mongorestore_test.go
In several places we used t.Errorf (i.e., fail the test, but continue) when the intent appears to have been t.Fatalf (fail and stop the test). This changeset makes that substitution.
Also included is a bit more clarity in a few cases where we skip tests.
=> TOOLS-3279: Fix segmentation faults when tests fail.

common-pvt.yml, common.yml, release/platform/platform.go
Note that, due to the unavailability of MongoDB builds for this distribution, currently no tests run that require MongoDB (e.g., integration).
=> TOOLS-3062 Add Amazon Linux 2023 x86 builds.

common-pvt.yml, common.yml, release/platform/platform.go
Note that, due to the unavailability of MongoDB builds for this OS, currently no tests run that require MongoDB (e.g., integration).
=> TOOLS-3054 Add RHEL 9.0 ARM builds.

common.yml, release/platform/platform.go, release/platform/platform_test.go
Updated code comment in `platform.go` and changed arch names for releases on RHEL platforms.
=> TOOLS-3309 Use `aarch64` for releases on RHEL platforms

common/db/command.go, mongodump/mongodump.go, mongorestore/mongorestore.go
Fixes issues where `mongodump` crashed when run against Atlas Online Archive or AWS DocumentDB by handling their errors properly. This will still break if any of these error messages change in the future.
I tested by running my local `mongosync` binary against an online archive cluster directly, and against an AWS DocumentDB instance tunneled through EC2 (instructions [here](https://docs.aws.amazon.com/documentdb/latest/developerguide/connect-from-outside-a-vpc.html)).
=> TOOLS-3344 Fix issue where mongodump failed against Atlas Online Archive and AWS DocumentDB

mongorestore/mongorestore_archive_test.go, mongorestore/mongorestore_test.go
This change adds integration tests to verify the behavior of `mongodump` and `mongorestore` on collections in the `config` database.
=> TOOLS-3349 Add integration tests for config db dump and restore

common/db/namespaces.go, common/idx/idx.go, common/intents/intent.go, common/intents/intent_prioritizer_test.go, mongodump/metadata_dump.go, mongodump/mongodump.go, mongodump/mongodump_test.go, mongodump/prepare.go, mongoexport/mongoexport.go, mongorestore/restore.go
Fixes an issue where `mongodump` did not always preserve the order of options for a view or collection. This could result in different sort orders than expected on views. It is easily fixed by moving from the unordered `bson.M` type to the ordered `bson.D` type for collection options. Index options are still a `bson.M`, but the keys are `bson.D` so they are not affected by this issue.
I tested manually by viewing the metadata JSON files produced by `mongodump` on both this branch and master. I also verified that the added test succeeds every time on this branch, but fails most of the time on master.
=> TOOLS-3411 Fix issue where sort order of views was not always preserved on dump

buildscript/build.go
This PR bumps the minimum go version to 1.20.12.
=> TOOLS-3438 Bump minimum go version to 1.20.12

PLATFORMSUPPORT.md, binaryurl.py, common-pvt.yml, common.yml, common/options/options.go, common/options/options_test.go, installer/msi/BinaryFragment.wxs, installer/rpm/mongodb-database-tools.spec, release/platform/platform.go, release/release.go, test/qa-tests/README.md
This also removes some internal code that checked for a `BuiltWithSSL` var that was always true.
=> TOOLS-3499 Remove all tests and config for the long obsolete sasl and ssl build tags

build.go, buildscript/build.go, common.yml, common/options/options_test.go, common/testtype/types.go, evergreen/evergreen.go
This PR fixes an issue with the Evergreen config for our lint-js testing.
It fixes the SRV tests by mocking DNS so we no longer rely on a particular cluster existing in Atlas when the tests are run. Since these tests are no longer special, the `test:srv` build target is gone and these tests are just run as normal unit tests.
It also cleans up the options testing code to use testify.
=> Fix lint-js and SRV test failures and clean up options testing code

.gitignore, common.yml, ssdlc/SBOM.v100.9.5.json
This adds the augmented SBOM for the next release.
It also updates our Evergreen config so that it checks that this file exists as part of the release. If it doesn't, the release will be aborted.
Finally, it adds a new Evergreen parameter, `fake_tag_for_release_testing`, which can be used to test things like this new task. It will set the `EVG_TRIGGERED_BY_TAG` env var without actually triggering a release, which an actual tag would do.
=> TOOLS-3550 Add the augmented SBOM file for the 100.9.5 release and add a release check for this file

common/idx/index_catalog_test.go, mongorestore/mongorestore_test.go
This test checks expects an error when restoring a timeseries collection where its `system.buckets` already exists. This no longer causes an error with 8.0.
=> TOOLS-3551 Fix mongorestore test failure with Server 8.0+

common.yml
Right now it uses `go.mod` by default, but if for some reason we ever added a deps file for another language, like a `package.json`, it might start testing that instead.
=> Pass `--file=./go.mod` to `snyk test`

common.yml, release/env/env.go, release/release.go
If this env var is true then it will block doing a real release. This provides a bit of extra safety when using this fake tag param.
=> TOOLS-3550 Set `IS_FAKE_TAG` env var when `fake_tag_for_release_testing` param is set

scripts/regenerate-and-diff-augmented-sbom.sh, ssdlc/100.9.5.bom.json
The `check-augmented-sbom` task gets called for `master` branch runs, not just releases, so we can't assume it will always be run when there's a tag to be checked.
This also updates the Augmented SBOM file to account for changes to our deps that were merged in other PRs.
=> TOOLS-3550 Make `regenerate-and-diff-augmented-sbom.sh` exit 0 when there's no tag

common.yml
Generating the SARIF report doesn't depend on the code being pushed anywhere.
=> Remove the `push` task dependency for the `gosec-SARIF-report` task

common.yml, scripts/write-evergreen-config-file.sh
This task never worked properly, but in the past `evergreen validate` would incorrectly exit with `0` when it couldn't authenticate itself.
=> Write out an `.evergreen.yml` file before running `evergreen validate`

release/release.go, release/version/version.go, scripts/set-expansions-for-papertrail.sh
* When creating a `version.Version`, we should not include the commit in the struct if we have a proper release tag. This fixes an issue where filenames for artifacts from a release tag incorrectly included the git commit.
* Fixed a bug in a script used for Papertrail integration where release tags caused the script to just fail.
* Improved some logging.
=> Fix several issues in the release code

cyclonedx.sbom.json
This added a new `"vulnerabilities": []` key. This isn't a _meaningful_ change, but if it's missing from the checked-in file then the `check-sbom-lite` task fails.
=> Update the SBOM Lite with the latest version of the Silkbomb tool

.gitignore, release/release.go, release/version/version.go, release/version/version_test.go
For non-stable releases, we want to use `VERSION~DATE.COMMIT` (e.g. ` mongodb-database-tools_100.9.5+20240619.d8f2d106_amd64.deb`) in the Debian package name. For stable releases, the commit should not be included.
This also removes the `Pre` field from the version. This was no longer used with our current tagging scheme, because we're not doing rc releases.
=> TOOLS-3572 Fix the version used for Debian packages and add tests for version code

scripts/regenerate-and-diff-augmented-sbom.sh
This is a real mess. It's not clear what flags we need to pass, nor when the behavior is correct. But I think this change will let us get the release out.
=> Don't pass `--no-update-*` flags to silkbomb

RELEASE.md
The automation in [PROG-11233](https://jira.mongodb.org/browse/PROG-11233) means we no longer have to do any manual work for these.
=> Fix header and link in release docs

buildscript/sa.go
[ubi](https://github.com/houseabsolute/ubi) recently changed its bootstrap mechanism, which has broken linting in Evergreen CI.
This changeset fixes that by downloading the bootstrap script for the ubi version that this project’s build system uses.
=> Fix Ubi download

common.yml
MacOS 10.14 is years out of date and being removed. I have run a successful patch with these changes.
=> DEVPROD-6063: run signing on macos 11

common.yml, scripts/sign_artifacts.sh
This commit templates our authenticode key name in preparation for the authenticode 2021 deprecation. The variable will be added to our Evergreen project as mongo-authenticode-2024.
=> DEVPROD-13316: template authenticode key name

CONTRIBUTING.md, RELEASE.md
This also adds some links to our internal wiki for more information on handling vulnerabilities in third-party dependencies.
=> Update release docs to say we should look at Jira for open vulnerabilities, not Silk

release/release.go
4.4 is EOL, so we can’t push it for server releases anymore. (This is blocking the next release.)
=> Delete 4.4 from releases.

ssdlc/100.11.0.bom.json
Per the latest builds, this needs to be rebuild before 100.11.0 can be released.
=> Redo 100.11.0’s augmented SBOM.

buildscript/sa.go, package-lock.json, package.json
I mostly did this to get a new `ubi` version, since that has a fix for an issue that one of our team members encountered.
This does _not_ upgrade the following:
* `eslint` - would require rewriting our config to a new format
* `golangci-lint` - would require fixing a bunch of new issues it found.
* `gosec` - also finds new issues, all of which appear to be spurious, but this deserves its own PR with a bit more attention.
=> Update most of our dev tools to their latest versions

buildscript/sa.go, common/bsonutil/converter.go, common/bsonutil/converter_test.go, common/bsonutil/marshal_d_test.go, common/bsonutil/timestamp_test.go, common/intents/intent_prioritizer.go, common/intents/intent_prioritizer_test.go, common/json/bindata.go, common/json/date.go, common/json/encode.go, common/json/tagkey_test.go, common/json/timestamp.go, common/util/math.go, mongodump/mongodump_test.go, mongoexport/csv.go, mongoimport/common_test.go, mongoimport/csv_test.go, mongoimport/typed_fields_test.go, mongorestore/metadata.go, mongorestore/mongorestore_test.go, mongorestore/mongorestore_txn_test.go, mongorestore/restore.go, release/release.go
This required adding error-checks to many type assertions. (Curiously, the prior golangci-lint _was_ configured to check those!)
A couple spots have no avenue for returning errors, so they’re left as-is with `//nolint` annotations.
=> Update golangci-lint to latest version.

common.yml
Turns out empty expansions.update doesn't update the variable, my testing was wrong.
=> common.yml: expansions.update correctly for kondukto_token

scripts/sign_artifacts.sh
This reduces spurious load on Apple’s macOS notary service.
=> TOOLS-3820 Only notarize when releasing

cyclonedx.sbom.json, release/platform/platform.go, release/release.go, scripts/regenerate-sbom-lite.sh
Previously, the SBOM would only contain dependencies that were used in the platform on which we generated the SBOM Lite file. We didn't notice this because we did not have any platform-conditional dependencies, but Jane was working on a PR that did add such a dep.
This changes the code that generates the SBOM Lite to get a list of deps for each of our supported platforms.
This _also_ changes the SBOM generation to only look at dependencies of the code for each of the release binaries. Previously, we included all the deps for everything in the repo. There were a huge number of packages that were only used by dev tooling, but not in the released tools.
=> TOOLS-3903 Always include all deps for all platforms in SBOM and only include deps for released binaries

.gitignore, cyclonedx.sbom.json
This also include s a change to `.gitignore` to ignore `/mise.toml`.
I want to use `mise` to manage Go locally, but I don't want to convert the whole repo to using `mise` right now.
=> TOOLS-3928 Update the SBOM Lite file

mongodump_passthrough/functions.yml
There are some build failures in the `t_resmoke_setup` step which have already been fixed in mongosync, so I'm updating the mongosync pin to the latest commit to pull those fixes in.
=> update _mongosync_pin in passthrough tests

SARIF.json, common.yml, release/notarize/notarize.go, release/release.go, ssdlc/100.13.0.sarif.json
This includes a grab bag of fixes for issues discovered while trying to release 100.13.0:
* Removed leading slashes from the S3 release paths. The new version of the AWS SDK Go library is pickier about paths.
* The `spctl` program is not in the default path on the Evergreen macOS hosts, so we call it with the fully-qualified path, `/usr/sbin/spctl`.
* The Evergreen config to check the SARIF report was not correct.
* The SARIF report was out of date and needed to be updated for 100.13.0.
=> Fix some Evergreen config and release code

mongodump_passthrough/tasks.yml, release/release.go, ssdlc/100.13.0.bom.json
This also includes an update to the Augmented SBOM. This adds a bogus vulnerability, but this is because of a bug in Kondukto that cannot be fixed today.
=> Fix S3 path when uploading release feed and don't run some tasks on git tag

cyclonedx.sbom.json, scripts/regenerate-sbom-lite.sh
We fixed this earlier by omitting the `.Module` structs that didn't contain `.Path`, but that was removed by mistake in #810. 
Rather than add it back and depend on `.Path` being empty, I'm adding a filter to remove the main module. This is indicated in the go list json by `.Main` being set to true in the `.Module` struct.
=> TOOLS-3964: omit the main module from go list for sbom generation
